version: "3.8"
services:
  db:
    env_file: .env
    image: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - '8000:8000'
volumes:
  postgres_data: