version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: fhir
    ports:
      - '5432:5432'
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - '8000:8000'
volumes:
  postgres_data: